### ISSUE TITLE
关于parent是否有问题

### ISSUE THREAD

**Issue by zhizhunbao995** [erzu/yen#25]
js
``` js
  onTrigger: function (e) {
    var self = this
    var root = self.el()
    var el = $(e.target)
    var trigger = el.hasClass('j-trigger') ? el : el.parent('.j-trigger')
```
html
``` html
<a class="trigger j-trigger" href="xxx" target="_blank" data-index="0">
	<img src="xxx">
</a>'
```
html结构一样 在mouseover到缩略图上触发onTrigger方法，发现trigger的返回值 在chrome 和ie 下返回不一样 ;chrome 为1 ，ie下0

**Comment by dotnil** [comment]
我还没时间验证这个问题，不过大致确认了，应该是这样的：

1. yen 支持直接传入节点，类似 `$(document.body)`
2. yen 支持指定 context，如果要查询 iframe 中的节点，需要这样 `$('body', iframe.contentDocument)`
3. yen 会用初始化 yen 的 scope 下的 document 作为默认的 context

结合这三点，假如传入的节点是 iframe 中的节点，但又没指定 context，就出问题了。这个时候 yen 需要根据传入的节点设定正确的 context，而不是直接用默认的 document。
