### ISSUE TITLE
Add .prop() 

### ISSUE THREAD

**Issue by yisibl** [erzu/yen#37]
表单元素上使用 `.attr()` 会有一些问题：
http://stackoverflow.com/questions/6048022/jquery-attrdisabled-disabled-not-working-in-chrome

jQuery 1.6 更新说明：
http://blog.jquery.com/2011/05/10/jquery-1-6-1-rc-1-released/

**Comment by dotnil** [comment]
http://stackoverflow.com/questions/5874652/prop-vs-attr
